version: '3' 
services:
  laravel-docker:
    container_name: mine-docker 
    build: .  
    volumes:
    - .:/var/www/html
    ports:
    - 9005:80

  mysql:
    image: mysql:latest 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Picard 
    ports:
    - 3305:3306

  phpmyadmin:
    image: phpmyadmin:latest 
    ports:
      - 9015:80 
    environment:
      - PMA_ARBITRARY=1