version: "3.9"
services:
    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: Picard
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
