version: "3.9"
services:
    mysql:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: Picard
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql

    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8080:8080

    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
        depends_on:
            - mysql
            - webserver

    webserver:
        image: nginx:alpine
        tty: true
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
    dbdata:
